name: Diamond
main: Diamonds.vdr.DiamondsPlugin.Main
version: alo-rant 1.5
settings:
  build-limit: 100
  build-low-limit: 40
  connection-throttle: 4000
  
commands:
  diamond:
    description: A Diamond Command.
    usage: Diamond Command is done
